//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections;
using System;
using UnityEngine;

public class SingletonClass<T> where T : class
{
	
	protected static T instance = null;
	//protected static AccountScript instance_a = null;
	public static T GetInstance{
		get{
			//if(Application.platform != RuntimePlatform.Android)
			//	return new GoogleScript();
			
			
			
			if(instance == null){
				instance = getClass<T>();
				if(instance == null){
					Debug.Log("not found instance : " + instance);
					return null;
				}
			}
			return instance;
		}
	}
	
	//어떠한 클래스 형으로도 new 제작
	private static T getClass<T>(){
		return (T)Activator.CreateInstance (typeof(T));
	}

	public virtual void initInstance(){
		instance = GetInstance;
	}
	
}



